# @package _global_
defaults:
  - /core/base@
  - /default_pretrain@
  - /hardware/cpu@hardware
  - /model/dinov2_test@model
  - _self_

task: PT001_ClevelandCCF
root: base
stem: debug

hardware:
  num_workers: 4

lightning:
  lightning_module: DINOv2Module

transforms:
  cpu_tr_transforms: dinov2
  cpu_val_transforms: dinov2
  gpu_tr_transforms: none
  gpu_val_transforms: none
  _cpu_tr_transforms:
    global_view_size: ${training.global_crop_size}
    local_view_size: ${training.local_crop_size}
  _cpu_val_transforms:
    global_view_size: ${training.global_crop_size}
    local_view_size: ${training.local_crop_size}
    
model:
  dimensions: 3D

data:
  train_split: split_40_10_50
  
training:
  patch_size: [16,16,16]
  global_crop_size: [64,64,64]
  local_crop_size: [32,32,32]
  batch_size: 2
  steps_per_epoch: 50
  val_steps_per_epoch: 0
  epochs: 5

logger:
  progress_bar: True
  profile: False
  wandb_log_model: False
  wandb_logging: False
  mlflow_logging: False
  log_every_n_steps: 1
  log_images_every_n_epoch: 1